# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.idInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.idInput.setGeometry(QtCore.QRect(282, 110, 251, 41))
        self.idInput.setObjectName("idInput")
        self.radioJane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioJane.setGeometry(QtCore.QRect(350, 260, 95, 20))
        self.radioJane.setObjectName("radioJane")
        self.radioJonh = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioJonh.setGeometry(QtCore.QRect(350, 300, 95, 20))
        self.radioJonh.setObjectName("radioJonh")
        self.submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(310, 350, 201, 41))
        self.submitButton.setObjectName("submitButton")
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(320, 460, 171, 31))
        self.statusLabel.setObjectName("statusLabel")
        self.idLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(190, 110, 71, 41))
        self.idLabel.setObjectName("idLabel")
        self.candidateLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidateLabel.setGeometry(QtCore.QRect(310, 200, 201, 41))
        self.candidateLabel.setObjectName("candidateLabel")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(290, 20, 251, 51))
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.viewHistoryButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.viewHistoryButton.setGeometry(QtCore.QRect(580, 10, 201, 41))
        self.viewHistoryButton.setObjectName("viewHistoryButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioJane.setText(_translate("MainWindow", "Jane"))
        self.radioJonh.setText(_translate("MainWindow", "Jonh"))
        self.submitButton.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.statusLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#aa0000;\">Already Voted</span></p></body></html>"))
        self.idLabel.setText(_translate("MainWindow", "     ID"))
        self.candidateLabel.setText(_translate("MainWindow", "     CANDIDATES"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">VOTING APPLICATION</span></p></body></html>"))
        self.viewHistoryButton.setText(_translate("MainWindow", "ACCESS HISTORY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
