# Form implementation generated from reading ui file 'vote_history.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.VoteHistoryWindow = QtWidgets.QTableWidget(parent=Dialog)
        self.VoteHistoryWindow.setGeometry(QtCore.QRect(10, 10, 371, 241))
        self.VoteHistoryWindow.setObjectName("VoteHistoryWindow")
        self.VoteHistoryWindow.setColumnCount(0)
        self.VoteHistoryWindow.setRowCount(0)
        self.closeButton = QtWidgets.QPushButton(parent=Dialog)
        self.closeButton.setGeometry(QtCore.QRect(290, 260, 93, 28))
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.closeButton.setText(_translate("Dialog", "CLOSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
